# Use root/example as user/password credentials
services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: egham4
      MONGO_INITDB_ROOT_PASSWORD: egham4
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: egham4
      ME_CONFIG_MONGODB_ADMINPASSWORD: egham4
      ME_CONFIG_MONGODB_URL: mongodb://egham4:egham4@mongo:27017/
      ME_CONFIG_BASICAUTH: false
